Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using TechMarket.Models;

namespace TechMarket.Controllers
{
    [Authorize(Roles = ClsRoles.roleAdmin)]
    public class AdminController : Controller
    {
        private readonly IProductRepo _productRepo;
        private readonly IUserRepo _userRepo;
        private readonly IUserService _userService;
        private readonly IOrderRepo _orderRepo;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public AdminController(IProductRepo productRepo,
            IUserRepo userRepo,
            IUserService userService,
            IOrderRepo orderRepo,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager )
        {
            _productRepo = productRepo;
            _userRepo = userRepo;
            _userService = userService;
            _orderRepo = orderRepo;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            //get all products
            var products = await _productRepo.GetAll();
            ViewBag.TotalUsers = _userRepo.Count();
            ViewBag.TotalProducts = await _productRepo.GetCountAllProducts();
            ViewBag.Products = "Products";
            return View(products);
        }
        public async Task<IActionResult> DisplayUsers()
        {
            var users = await _userRepo.GetUsers();
            ViewBag.Users = "Users";
            return View(users);
        }
        public async Task<IActionResult> DisplayOrders()
        {
            var orders = await _orderRepo.GetOrders();
            ViewBag.Orders = "Orders";
            return View(orders);
        }
        public async Task<IActionResult> DisplayOrderDetails(int orderId)
        {
            var order = await _orderRepo.GetOrderById(orderId);
            return View(order);
        }

        public IActionResult ChangeProductState(int productId)
        {
            var isChanged = _productRepo.ChangeProductState(productId);
            if (isChanged == -1)
            {
                return BadRequest();
            }
            return RedirectToAction("Details", "Product", new { id = productId });
        }

        [HttpPost]
        public IActionResult SubmitForm(string action, string? message, int productId)
        {
            //if (action == "Accept")
            //{
            //    // Handle Accept logic
            //}
            //else if (action == "Reject")
            //{
            //    // Handle Reject logic
            //}


            // Handle the message and productId as needed
            // ...
            var Done = _productRepo.DoSome(action,message,productId);
            if (Done == -1)
            {
                return BadRequest();
            }
            return RedirectToAction("Details", "Product", new { id = productId });
        }




        public async Task<IActionResult> MyProducts()
        {
            return View(await _productRepo.GetAll(_userService.GetUserId()));
        }
        public async Task<IActionResult> addRoles(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            var userRoles = await _userManager.GetRolesAsync(user);

            var allRoles = await _roleManager.Roles.ToListAsync();
            if (allRoles != null)
            {
                var roleList = allRoles.Select(r => new RoleViewModel()
                {
                    roleId = r.Id,
                    roleName = r.Name,
                    useRole = userRoles.Any(x => x == r.Name)
                });
                ViewBag.userName = user.UserName;
                ViewBag.userId = userId;
                return View(roleList);
            }
            else
                return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> addRoles(string userId, string jsonRoles)
        {
            var user = await _userManager.FindByIdAsync(userId);

            List<RoleViewModel> myRoles =
                JsonConvert.DeserializeObject<List<RoleViewModel>>(jsonRoles);

            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);

                foreach (var role in myRoles)
                {
                    if (userRoles.Any(x => x == role.roleName.Trim()) && !role.useRole)
                    {
                        await _userManager.RemoveFromRoleAsync(user, role.roleName.Trim());
                    }

                    if (!userRoles.Any(x => x == role.roleName.Trim()) && role.useRole)
                    {
                        await _userManager.AddToRoleAsync(user, role.roleName.Trim());
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
                return NotFound();
        }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using System.Diagnostics;

namespace TechMarket.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IOrderRepo _orderRepo;
        private readonly ICartRepo _cartRepo;
        private readonly IProductRepo _productRepo;
        private readonly IUserService _userService;
        private readonly string _userId;
        public CartController(ICartRepo cartRepo, IProductRepo productRepo, IUserService userService, IOrderRepo orderRepo)
        {
            _cartRepo = cartRepo;
            _productRepo = productRepo;
            _userService = userService;
            _userId = _userService.GetUserId();
            if (string.IsNullOrEmpty(_userId))
            {
                throw new UnauthorizedAccessException("You must be logged in to perform this action");
            }
            _orderRepo = orderRepo;
        }
        public IActionResult Index()
        {
            var cart = _cartRepo.GetCartByUserId(_userId);

            if (cart == null)
            {
                return BadRequest();
            }
            return View(cart);


        }
        [HttpPost]
        public IActionResult AddToCart(int productId)
        {
            var isAdded = _cartRepo.AddToCart(productId);
            if (isAdded == 1)
            {
                return Json(new { success = "added" });
            }
            else if(isAdded == -1) // the product is already in your cart
            {
                return Json(new { success = "isExisted" });
            }
            return Json(new { success = "failed" });
        }
        public IActionResult RemoveFromCart(int productId)
        {
            var isDeleted = _cartRepo.RemoveFromCart(productId);
            if(isDeleted == -1)
            {
                return BadRequest();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CheckOut()
        {
            ViewBag.cartId = _cartRepo.GetCartByUserId(_userId).Id;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CheckOut(Order order)
        {
            if (!ModelState.IsValid)
            {
                return View(order);
            }
            
            var isAdded = _orderRepo.Add(order);
            if(isAdded != 1)
            {
                return BadRequest();   
            }
            ViewData["orderIsAdded"] = "your order has been sent to the center";
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateQuantity(int productId, int quantity)
        {
            if (quantity <= 0)
            {
               // var cart = _cartRepo.GetCartByUserId(_userId);
                TempData["ErrorMessage"] = "The minimum quantity for each product is 1";
                return RedirectToAction("Index");
            }
            var isUpdated = _cartRepo.UpdateCartContentQuantity(productId, quantity);
            if(isUpdated == -1)
            {
                return BadRequest();
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TechMarket.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderRepo _orderRepo;
        private readonly IUserService _userService;
        private readonly string _userId;
        public OrderController(IOrderRepo orderRepo,IUserService userService)
        {
            _orderRepo = orderRepo;
            _userService = userService;
            _userId = _userService.GetUserId();
            if (string.IsNullOrEmpty(_userId))
            {
                return;
                //throw new UnauthorizedAccessException("You must be logged in to perform this action");
            }
        }
        public async Task<IActionResult> Index()
        {
            var orders = await _orderRepo.GetOrders(_userId);
            return View(orders);
        }
        public async Task<IActionResult> Details(int orderId)
        {
            var order = await _orderRepo.GetOrderById(orderId);
            return View(order);
        }
    }
}

Views/Shared/_AdminLayout.cshtml
﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    @* BootStrap *@
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />

    <!--DtataTable-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.bootstrap5.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.2/css/responsive.bootstrap5.css" />

    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/admin.css" />
    <style>
        a:hover{
            text-decoration:none;
        }
    </style>

</head>
<body>
    <div class="main-contaier">

        @* side nav bar *@
        <nav class="sidenav list-group">

            <a class="navigation-link" asp-controller="Admin" asp-action="DisplayUsers"><i class="bi bi-people fa-lg"></i> <span class="d-none d-md-inline">Users</span></a>
            <a class="navigation-link" asp-controller="Admin" asp-action="Index"><i class="bi bi-table fa-lg"></i> <span class="d-none d-md-inline">Products</span> </a>
            <a class="navigation-link" asp-controller="Admin" asp-action="DisplayOrders"><i class="bi bi-basket3 fa-lg"></i> <span class="d-none d-md-inline">Orders</span></a>
            <a class="navigation-link text-danger" style="font-size:20px" asp-controller="Home" asp-action="Stock"><i class="bi bi-box-arrow-right fa-lg"></i> <span class="d-none d-md-inline">Exit</span></a>

        </nav>
        @*  upper nav bar *@
        <div class="right-panel">
            <nav class="nav-bar fixed-top">
                <div class="nav-heading">Welcome @User.Identity?.Name</div>
                <div class="nav-heading">
                @ViewData["Title"]
                </div>
                <div class="nav-actions">
                    <a href="/Identity/Account/Manage/Index" class="navigation-link"><i class="bi bi-gear"></i> Manage account</a>
                </div>
            </nav>
            <div class="content container">
                @RenderBody()
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap core JS-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <!--DtataTable-->
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js "></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.js "></script>
    <script>
        $(document).ready(function () {
            $('#page').DataTable({ responsive: true });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   @*  <link rel="stylesheet" href="~/css/bootstrape.css" /> *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TechMarket.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark ">

            <a asp-controller="Home" asp-action="HomePage" class="navbar-brand">Tech</a>
            <button class="navbar-toggler" style="" type="button" data-bs-toggle="collapse" data-bs-target="#items" aria-controls="items" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
           
            <div id="items" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Stock">Shop</a>
                    </li>
                  
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                     @if (User.Identity.IsAuthenticated)
                    {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Manage
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Products</a></li>
                            <li><a class="dropdown-item" asp-controller="Cart" asp-action="Index">Cart</a></li>
                            <li><a class="dropdown-item" asp-controller="Order" asp-action="Index">Orders</a></li>
                        </ul>
                    </li>
                    }
                </ul>
                <form class="d-flex" asp-controller="Home" asp-action="Stock" method="get">
                    <input name="seachName" value="@ViewBag.seachName" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-warning my-2 my-lg-0" type="submit">Search</button>
                </form>

                <partial name="_LoginPartial" />
                
                   
               
            </div>
           
     
        </nav>
    </header>
    <div id="popup-container" class="popup-container">
        <div class="popup-content col-10" style="width:75%">
            <span class="close-button">&times;</span>
            <h2>About</h2>
            <p>Teck Market is a leading online platform that offers a wide range of high-quality products at competitive prices. From household essentials to the latest electronics, we have it all. Our user-friendly interface and fast, secure delivery make shopping a breeze.</p>
        </div>
    </div>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="text-center text-lg-start bg-body-tertiary text-muted">
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Tech Market
                        </h6>
                        <p>
                            Teck Market is a leading online platform that offers a wide range of high-quality products at competitive prices.
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Products
                        </h6>
                      
                        
                        <p>
                             <a class="text-reset" asp-controller="Home" asp-action="Stock" asp-route-categoryName="Computer">Computer</a>
                        </p>
                        <p>
                            <a class="text-reset" asp-controller="Home" asp-action="Stock" asp-route-categoryName="Tablet">Tablet</a>
                        </p>
                        <p>
                            <a class="text-reset" asp-controller="Home" asp-action="Stock" asp-route-categoryName="Mobile">Mobile</a>
                        </p>
                       
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                        </h6>
                        <p>
                            <a asp-controller="Product" asp-action="Index" class="text-reset">My Products</a>
                        </p>
                        <p>
                            <a asp-area="Identity" asp-page="/Account/Manage/Index" class="text-reset">Settings</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Feedback</a>
                        </p>
                        <p>
                            <a href="#!" id="about-btn" class="text-reset">About</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                        <p><i class="fas fa-home me-3"></i> Lattakia, Jablah, SYR</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            hasankassab@gmail.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> + 041 8 825 428 </p>
                        <p><i class="fas fa-print me-3"></i> + 963 991 097 251</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
            <div class="text-center">
                <a href="https://www.facebook.com/ifisaysomethingimeanit" target="_blank" class="me-4 text-reset">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="https://www.linkedin.com/in/hasan-kassab-463881231/" target="_blank" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="https://github.com/hasandex/" target="_blank" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2024 Copyright:
            <a class="text-reset fw-bold" href="#">Example.com</a>
        </div>
        <!-- Copyright -->
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js "></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.js "></script>
    <script>
        $(document).ready(function () {
            $('#page').DataTable({ responsive: true });
        });
    </script>
    <script>
        const aboutBtn = document.getElementById('about-btn');
        const popupContainer = document.getElementById('popup-container');
        const closeButton = document.querySelector('.close-button');

        aboutBtn.addEventListener('click', () => {
            popupContainer.classList.add('fade-in-out');
        });

        closeButton.addEventListener('click', () => {
            popupContainer.classList.remove('fade-in-out');
        });

        window.addEventListener('click', (event) => {
            if (event.target === popupContainer) {
                popupContainer.classList.remove('fade-in-out');
            }
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>